# Generated by Django 3.1.5 on 2021-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='peers',
            field=models.ManyToManyField(related_name='network', to='users.Profile'),
        ),
    ]
