# Generated by Django 3.1.5 on 2021-01-21 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default='2021-01-21 12:21:00')),
                ('is_protected', models.BooleanField(default=False)),
                ('date_protected', models.DateTimeField(default='2021-01-21 12:21:00')),
                ('previous_hash_code', models.CharField(max_length=64)),
                ('hash_code', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
