# Generated by Django 3.1.5 on 2021-01-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notechainapp', '0002_auto_20210121_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.CharField(default='2021-01-21 12:28:13', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_protected',
            field=models.CharField(default='2021-01-21 12:28:13', max_length=20),
        ),
    ]
