# Generated by Django 3.1.5 on 2021-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notechainapp', '0003_auto_20210121_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_protected',
            field=models.CharField(max_length=20),
        ),
    ]
