# Generated by Django 3.1.5 on 2021-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notechainapp', '0004_auto_20210121_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_protected',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='hash_code',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='note',
            name='previous_hash_code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
